"""Private, create-only local storage for the initial deployment.

Keys are generated by the server and never exposed as public download URLs.
Atomic hard-link publication prevents a reused upload URL from replacing bytes.
"""

from __future__ import annotations

import hashlib
import os
import re
import socket
import struct
import time
from dataclasses import dataclass
from pathlib import Path
from typing import AsyncIterable


MAX_FILE_BYTES = 20 * 1024 * 1024
ALLOWED_TYPES = {"application/pdf", "image/jpeg", "image/png"}
KEY = re.compile(r"^[a-f0-9]{32}$")


class StorageError(Exception):
    def __init__(self, code: str):
        self.code = code
        super().__init__(code)


def private_path(root: str | Path, key: str) -> Path:
    if not KEY.fullmatch(key):
        raise StorageError("INVALID_OBJECT_KEY")
    directory = Path(root).resolve()
    directory.mkdir(parents=True, exist_ok=True, mode=0o700)
    return directory / key


def detect_type(header: bytes) -> str | None:
    if header.startswith(b"%PDF-"):
        return "application/pdf"
    if header.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if header.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    return None


async def store_once(
    root: str | Path,
    key: str,
    chunks: AsyncIterable[bytes],
    expected_size: int,
    declared_type: str,
) -> tuple[int, str, str]:
    """Persist one immutable object, never replacing an existing object.

An interrupted .part file blocks reuse until its upload intent is cleaned up;
callers can create a fresh intent. No referenced final object is ever removed.
"""
    target = private_path(root, key)
    if target.exists():
        raise StorageError("UPLOAD_ALREADY_USED")
    partial = target.with_suffix(".part")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(partial, flags, 0o600)
    except FileExistsError as exc:
        raise StorageError("UPLOAD_ALREADY_USED") from exc
    try:
        digest = hashlib.sha256()
        size = 0
        header = bytearray()
        with os.fdopen(descriptor, "wb") as output:
            async for chunk in chunks:
                if not isinstance(chunk, bytes):
                    raise StorageError("INVALID_UPLOAD")
                size += len(chunk)
                if size > min(expected_size, MAX_FILE_BYTES):
                    raise StorageError("FILE_TOO_LARGE")
                if len(header) < 32:
                    header.extend(chunk[: 32 - len(header)])
                digest.update(chunk)
                output.write(chunk)
            if size != expected_size or size < 1:
                raise StorageError("OBJECT_INCOMPLETE")
            detected = detect_type(bytes(header))
            if detected is None or detected != declared_type:
                raise StorageError("FILE_TYPE_MISMATCH")
            output.flush()
            os.fsync(output.fileno())
        try:
            os.link(partial, target, follow_symlinks=False)
        except FileExistsError as exc:
            raise StorageError("UPLOAD_ALREADY_USED") from exc
        parent_fd = os.open(target.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(parent_fd)
        finally:
            os.close(parent_fd)
        return size, digest.hexdigest(), detected
    finally:
        # This request exclusively created .part; only that temporary file is
        # removed. An already-published final object remains immutable.
        partial.unlink(missing_ok=True)


def inspect_object(root: str | Path, key: str) -> tuple[int, str, str | None]:
    path = private_path(root, key)
    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as exc:
        raise StorageError("OBJECT_INCOMPLETE") from exc
    size = 0
    digest = hashlib.sha256()
    header = b""
    with os.fdopen(descriptor, "rb") as source:
        while chunk := source.read(1024 * 1024):
            if not header:
                header = chunk[:32]
            size += len(chunk)
            if size > MAX_FILE_BYTES:
                raise StorageError("FILE_TOO_LARGE")
            digest.update(chunk)
    return size, digest.hexdigest(), detect_type(header)


@dataclass(frozen=True)
class ScanResult:
    status: str
    engine: str
    error: str | None = None


def scan_object(path: Path, settings) -> ScanResult:
    """Production accepts CLEAN only after the configured ClamAV returns OK."""
    engine = settings.scan_backend
    if engine == "development":
        if settings.app_env == "production":
            return ScanResult("SCAN_FAILED", "disabled", "DEV_SCANNER_FORBIDDEN")
        try:
            with path.open("rb") as stream:
                detected = detect_type(stream.read(32))
        except OSError:
            return ScanResult("SCAN_FAILED", "development-format-only-NOT-ANTIVIRUS", "OBJECT_UNAVAILABLE")
        return ScanResult(
            "CLEAN" if detected else "REJECTED",
            "development-format-only-NOT-ANTIVIRUS",
            None if detected else "FILE_TYPE_MISMATCH",
        )
    if engine != "clamav" or not settings.clamav_host:
        return ScanResult("SCAN_FAILED", "unconfigured", "SCANNER_NOT_CONFIGURED")
    try:
        deadline = time.monotonic() + settings.clamav_timeout
        with socket.create_connection(
            (settings.clamav_host, settings.clamav_port), timeout=settings.clamav_timeout
        ) as connection:
            connection.settimeout(settings.clamav_timeout)
            connection.sendall(b"zINSTREAM\0")
            size = 0
            with path.open("rb") as source:
                while chunk := source.read(64 * 1024):
                    remaining = deadline - time.monotonic()
                    if remaining <= 0:
                        raise TimeoutError("Scanner deadline exceeded")
                    connection.settimeout(remaining)
                    size += len(chunk)
                    if size > MAX_FILE_BYTES:
                        return ScanResult("REJECTED", "clamav-instream", "FILE_TOO_LARGE")
                    connection.sendall(struct.pack("!I", len(chunk)))
                    connection.sendall(chunk)
            connection.sendall(struct.pack("!I", 0))
            response = bytearray()
            while len(response) < 4096:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    raise TimeoutError("Scanner deadline exceeded")
                connection.settimeout(remaining)
                chunk = connection.recv(4096 - len(response))
                if not chunk:
                    break
                response.extend(chunk)
                if b"\0" in response:
                    break
            answer = bytes(response).split(b"\0", 1)[0].strip()
            if answer == b"stream: OK":
                return ScanResult("CLEAN", "clamav-instream")
            if answer.endswith(b" FOUND"):
                return ScanResult("REJECTED", "clamav-instream", "UNSAFE_CONTENT")
            return ScanResult("SCAN_FAILED", "clamav-instream", "SCANNER_ERROR")
    except (OSError, TimeoutError):
        return ScanResult("SCAN_FAILED", "clamav-instream", "SCANNER_UNAVAILABLE")
