"""initial_schema

Revision ID: 78a60fc3915a
Revises:
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import app.db


revision: str = '78a60fc3915a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_verified_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('role_version', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('last_totp_step', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('auth_rate_limits',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_auth_rate_limits_expires_at'), 'auth_rate_limits', ['expires_at'], unique=False)
    op.create_table('schemes',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('form_schema', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_inbox',
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'event_id')
    )
    op.create_table('cases',
    sa.Column('scheme_id', sa.String(length=36), nullable=False),
    sa.Column('case_no', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.Column('last_business_update_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_no')
    )
    op.create_index(op.f('ix_cases_assigned_to'), 'cases', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_cases_created_by'), 'cases', ['created_by'], unique=False)
    op.create_index(op.f('ix_cases_scheme_id'), 'cases', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('content_versions',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('published_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'code', 'version_no')
    )
    op.create_table('export_jobs',
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('filter_snapshot', sa.JSON(), nullable=False),
    sa.Column('column_set', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=True),
    sa.Column('case_ids', sa.JSON(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idempotency_records',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('route_scope', sa.String(length=300), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'method', 'route_scope', 'key')
    )
    op.create_table('identity_links',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=100), nullable=False),
    sa.Column('line_subject', sa.String(length=100), nullable=False),
    sa.Column('binding_version', sa.Integer(), nullable=False),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('observed_follow_status', sa.String(length=20), nullable=True),
    sa.Column('last_event_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_links_account_id'), 'identity_links', ['account_id'], unique=False)
    op.create_index('uq_active_line_account', 'identity_links', ['account_id'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('uq_active_line_subject', 'identity_links', ['provider_id', 'line_subject'], unique=True, sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('mfa_challenges',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_grants',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_grants_account_id'), 'role_grants', ['account_id'], unique=False)
    op.create_table('sessions',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=30), nullable=False),
    sa.Column('role_version', sa.Integer(), nullable=False),
    sa.Column('reauth_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_account_id'), 'sessions', ['account_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('case_access',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('grant_source', sa.String(length=30), nullable=False),
    sa.Column('verification_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_access_account_id'), 'case_access', ['account_id'], unique=False)
    op.create_index(op.f('ix_case_access_case_id'), 'case_access', ['case_id'], unique=False)
    op.create_table('case_revisions',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('form_snapshot', sa.JSON(), nullable=False),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'revision_no')
    )
    op.create_index(op.f('ix_case_revisions_case_id'), 'case_revisions', ['case_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verification_id', sa.String(length=200), nullable=True),
    sa.Column('resolved_case_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('public_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['resolved_case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decisions',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rule_version_id', sa.String(length=100), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=False),
    sa.Column('decided_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_case_id'), 'decisions', ['case_id'], unique=False)
    op.create_table('domain_events',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('resource_version', sa.Integer(), nullable=False),
    sa.Column('public_payload', sa.JSON(), nullable=False),
    sa.Column('occurred_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_events_case_id'), 'domain_events', ['case_id'], unique=False)
    op.create_table('email_challenges',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('request_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_challenges_email'), 'email_challenges', ['email'], unique=False)
    op.create_index(op.f('ix_email_challenges_request_ip_hash'), 'email_challenges', ['request_ip_hash'], unique=False)
    op.create_table('line_challenges',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('expires_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_items',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_code', sa.String(length=100), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('public_reason', sa.Text(), nullable=True),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'criterion_code')
    )
    op.create_index(op.f('ix_review_items_case_id'), 'review_items', ['case_id'], unique=False)
    op.create_table('tasks',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_revision_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('example_ref', sa.String(length=500), nullable=True),
    sa.Column('due_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('accepted_submission_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_case_id'), 'tasks', ['case_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('files',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_case_id'), 'files', ['case_id'], unique=False)
    op.create_table('notification_intents',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('task_revision', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('binding_version', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('scheduled_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('recipient_snapshot', sa.String(length=100), nullable=True),
    sa.Column('retry_key', sa.String(length=36), nullable=True),
    sa.Column('first_attempt_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['domain_events.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'purpose', 'channel', 'account_id')
    )
    op.create_index(op.f('ix_notification_intents_case_id'), 'notification_intents', ['case_id'], unique=False)
    op.create_index(op.f('ix_notification_intents_status'), 'notification_intents', ['status'], unique=False)
    op.create_table('submissions',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('task_revision', sa.Integer(), nullable=True),
    sa.Column('case_revision_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by', sa.String(length=36), nullable=False),
    sa.Column('submitted_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('file_version_ids', sa.JSON(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('deadline_snapshot', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['case_revision_id'], ['case_revisions.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_case_id'), 'submissions', ['case_id'], unique=False)
    op.create_index(op.f('ix_submissions_task_id'), 'submissions', ['task_id'], unique=False)
    op.create_table('task_revisions',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=False),
    sa.Column('example_ref', sa.String(length=500), nullable=True),
    sa.Column('due_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'revision_no')
    )
    op.create_index(op.f('ix_task_revisions_task_id'), 'task_revisions', ['task_id'], unique=False)
    op.create_table('file_versions',
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('declared_type', sa.String(length=100), nullable=False),
    sa.Column('detected_type', sa.String(length=100), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('scan_status', sa.String(length=30), nullable=False),
    sa.Column('scan_engine_version', sa.String(length=200), nullable=True),
    sa.Column('upload_token_digest', sa.String(length=64), nullable=True),
    sa.Column('upload_expires_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scanned_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scan_attempts', sa.Integer(), nullable=False),
    sa.Column('scan_retry_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('scan_lease_until', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_file_versions_file_id'), 'file_versions', ['file_id'], unique=False)
    op.create_index(op.f('ix_file_versions_scan_status'), 'file_versions', ['scan_status'], unique=False)
    op.create_table('notification_attempts',
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('retry_key', sa.String(length=36), nullable=True),
    sa.Column('payload_snapshot', sa.JSON(), nullable=False),
    sa.Column('first_attempt_at', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempted_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('provider_request_id', sa.String(length=100), nullable=True),
    sa.Column('accepted_request_id', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['notification_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_attempts_intent_id'), 'notification_attempts', ['intent_id'], unique=False)
    op.create_table('outbox_jobs',
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('available_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_until', app.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['notification_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id')
    )
    op.create_index(op.f('ix_outbox_jobs_available_at'), 'outbox_jobs', ['available_at'], unique=False)
    op.create_table('receipts',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_receipts_case_id'), 'receipts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_case_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_outbox_jobs_available_at'), table_name='outbox_jobs')
    op.drop_table('outbox_jobs')
    op.drop_index(op.f('ix_notification_attempts_intent_id'), table_name='notification_attempts')
    op.drop_table('notification_attempts')
    op.drop_index(op.f('ix_file_versions_scan_status'), table_name='file_versions')
    op.drop_index(op.f('ix_file_versions_file_id'), table_name='file_versions')
    op.drop_table('file_versions')
    op.drop_index(op.f('ix_task_revisions_task_id'), table_name='task_revisions')
    op.drop_table('task_revisions')
    op.drop_index(op.f('ix_submissions_task_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_case_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_notification_intents_status'), table_name='notification_intents')
    op.drop_index(op.f('ix_notification_intents_case_id'), table_name='notification_intents')
    op.drop_table('notification_intents')
    op.drop_index(op.f('ix_files_case_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_case_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_review_items_case_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('line_challenges')
    op.drop_index(op.f('ix_email_challenges_request_ip_hash'), table_name='email_challenges')
    op.drop_index(op.f('ix_email_challenges_email'), table_name='email_challenges')
    op.drop_table('email_challenges')
    op.drop_index(op.f('ix_domain_events_case_id'), table_name='domain_events')
    op.drop_table('domain_events')
    op.drop_index(op.f('ix_decisions_case_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_case_revisions_case_id'), table_name='case_revisions')
    op.drop_table('case_revisions')
    op.drop_index(op.f('ix_case_access_case_id'), table_name='case_access')
    op.drop_index(op.f('ix_case_access_account_id'), table_name='case_access')
    op.drop_table('case_access')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_sessions_account_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_role_grants_account_id'), table_name='role_grants')
    op.drop_table('role_grants')
    op.drop_table('mfa_challenges')
    op.drop_index('uq_active_line_subject', table_name='identity_links', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('uq_active_line_account', table_name='identity_links', sqlite_where=sa.text('revoked_at IS NULL'), postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_identity_links_account_id'), table_name='identity_links')
    op.drop_table('identity_links')
    op.drop_table('idempotency_records')
    op.drop_table('export_jobs')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_scheme_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_by'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_to'), table_name='cases')
    op.drop_table('cases')
    op.drop_table('webhook_inbox')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_auth_rate_limits_expires_at'), table_name='auth_rate_limits')
    op.drop_table('auth_rate_limits')
    op.drop_table('accounts')
    # ### end Alembic commands ###
